namespace SpriteKind {
    export const capture_point = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    bullet = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 5 5 5 . . . . . . . . 
        . . . . . . . . . . . 5 5 5 . . 
        . . . 5 5 5 . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 5 5 5 5 . 5 . . . . 
        . . . . 5 5 . . . . . . . . . . 
        . . . 5 . . . . . . . . . . . . 
        . . . . . . 5 5 5 5 5 5 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 5 5 5 5 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, foot_soldier, 100, 0)
    bullet.follow(myEnemy)
    pause(2000)
    sprites.destroy(bullet)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-0.01)
    sprites.destroy(myEnemy, effects.spray, 500)
})
info.onLifeZero(function () {
	
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(myEnemy)
    sprites.destroy(bullet, effects.disintegrate, 100)
})
let myEnemy: Sprite = null
let bullet: Sprite = null
let foot_soldier: Sprite = null
info.startCountdown(90)
foot_soldier = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ............fffff...............
    ...........f77777f..............
    ..........f7775577f.............
    ..........f77777777f............
    .........f77bbbbb77f............
    .........f7bbfbbfb7f............
    ..........fbbbbbbbf.............
    ...........fbfffbf..............
    ...........fbbbbbf...ff.........
    ............fbbbf...f55f........
    .............fbf....f55f........
    .............fbf....f55ffff.....
    ............f777f..f777777cf....
    ..........ff77777f.f777777cf....
    .........f7777755fffffccfff.....
    ........f7777777777777ccbf......
    .......f77ff7777777777ccbf......
    .......f77ff77777ffffffcff......
    .......f77ffee5eef....ff........
    .......fbbff77777f..............
    ........ff.fbfff77f.............
    ..........f77f.f7bf.............
    ..........f77f.f77f.............
    ..........f77f.f77f.............
    ..........f11f.feef.............
    .........f111f.feeef............
    .........ffff...ffff............
    `, SpriteKind.Player)
foot_soldier.setPosition(22, 91)
scene.setBackgroundImage(assets.image`background`)
info.setLife(20)
game.onUpdateInterval(2000, function () {
    myEnemy = sprites.create(assets.image`sunflower`, SpriteKind.Enemy)
    myEnemy.setPosition(147, 91)
    myEnemy.follow(foot_soldier)
    myEnemy.setScale(2, ScaleAnchor.Middle)
})
